version: '3.8'
services:
  notebook:
    ports:
    - "8888:8888"
    - "4040:4040"
    volumes:
    - type: bind
      source: .
      target: /home/jovyan/work
    image: "jupyter/pyspark-notebook"
